using CSharpFunctionalExtensions;
using OIO.Domain.Context.OrderContext.Enums;
using OIO.Domain.Context.OrderContext.Errors;
using OIO.Domain.Context.OrderContext.ValueObjects.Ids;
using OIO.Domain.Context.Shared.ValueObjects.Ids;
using OIO.Domain.SeedWork.Entities;
using OIO.Domain.SeedWork.Errors;

namespace OIO.Domain.Context.OrderContext.Aggregates.SellerDirectShipments;

/// <summary>
/// Seller-direct fulfillment shipment. Strict 1:1 with an Order. The seller
/// books their own carrier outside the platform; we only track the lifecycle
/// state machine and a QR deep-link the buyer can scan on package handover.
///
/// Lifecycle:
///   Draft → CarrierBooked → PickedUp → OnDelivering → Delivered → Accepted → Completed
///                                                              ↘ Disputed (one-way)
///
/// All progression methods are idempotent: calling them when already at or
/// past the target status returns success without mutating state.
/// </summary>
public sealed class SellerDirectShipment : AggregateRoot<SellerDirectShipmentId>
{
    private SellerDirectShipment() { }

    private SellerDirectShipment(
        SellerDirectShipmentId id,
        OrderId orderId,
        string shipmentIdDisplay,
        string internalTrackingCode,
        string qrPayload,
        string qrCodeUrl,
        DateTime nowUtc)
    {
        Id                   = id;
        OrderId              = orderId;
        ShipmentIdDisplay    = shipmentIdDisplay;
        InternalTrackingCode = internalTrackingCode;
        QrPayload            = qrPayload;
        QrCodeUrl            = qrCodeUrl;
        Status               = SellerDirectShipmentStatus.Draft;
        CreatedAt            = nowUtc;
        QrTokenVersion       = 1;
        ManualReviewRequired = false;
    }

    private readonly List<SellerDirectShipmentEvidence> _evidence = new();

    /// <summary>Evidence photos attached to this shipment (seller package, handover, buyer delivery).</summary>
    public IReadOnlyCollection<SellerDirectShipmentEvidence> Evidence => _evidence.AsReadOnly();

    public OrderId OrderId { get; private set; }

    /// <summary>Human-readable id, format <c>DSH-YYYYMMDD-NNNN</c>. Unique.</summary>
    public string ShipmentIdDisplay { get; private set; }

    /// <summary>Secure random opaque tracking code generated by the platform. Unique.</summary>
    public string InternalTrackingCode { get; private set; }

    /// <summary>Canonical payload/deep-link string to encode into a QR image client-side.</summary>
    public string QrPayload { get; private set; }

    /// <summary>Legacy/optional. DO NOT assume this is an image URL. FE must render QR from <see cref="QrPayload"/>.</summary>
    public string QrCodeUrl { get; private set; }

    public string? ExternalCarrierName { get; private set; }
    public string? ExternalTrackingCode { get; private set; }

    public SellerDirectShipmentStatus Status { get; private set; }

    public DateTime CreatedAt { get; private set; }
    public DateTime? ModifiedAt { get; private set; }
    public DateTime? CarrierBookedAt { get; private set; }
    public DateTime? PickedUpAt { get; private set; }
    public DateTime? OnDeliveringAt { get; private set; }
    public DateTime? DeliveredAt { get; private set; }
    public DateTime? BuyerReceivedPackageAt { get; private set; }
    public DateTime? BuyerAcceptedAt { get; private set; }
    public DateTime? DisputedAt { get; private set; }
    public DateTime? CompletedAt { get; private set; }

    // QR token lifecycle — version bumped on revoke; issued/revoked timestamps audit trail.
    public int QrTokenVersion { get; private set; }
    public DateTime? QrTokenIssuedAt { get; private set; }
    public DateTime? QrTokenRevokedAt { get; private set; }

    // Seller self-declared dispatch timestamp (separate from CarrierBookedAt/PickedUpAt).
    public DateTime? SellerDeclaredShippedAt { get; private set; }

    // Buyer package condition at receipt. Free string; enum enforced at app/API layer.
    // Allowed values: sealed_intact, outer_damage, wet_or_torn, tamper_suspected, wrong_parcel, other.
    public string? BuyerPackageCondition { get; private set; }
    public string? BuyerConditionNotes { get; private set; }

    // Manual review flag set when buyer reports non-intact condition or other anomalies.
    public bool ManualReviewRequired { get; private set; }
    public string? ManualReviewReason { get; private set; }

    public static SellerDirectShipment Create(
        Guid orderId,
        string shipmentIdDisplay,
        string internalTrackingCode,
        string qrPayload,
        string qrCodeUrl,
        DateTime nowUtc)
    {
        return new SellerDirectShipment(
            SellerDirectShipmentId.From(Guid.CreateVersion7()),
            OrderId.From(orderId),
            shipmentIdDisplay,
            internalTrackingCode,
            qrPayload,
            qrCodeUrl,
            nowUtc);
    }

    /// <summary>
    /// Overload that accepts a caller-supplied id so the QR payload/URL can
    /// embed the same id the aggregate will be persisted under (without a
    /// second update round-trip).
    /// </summary>
    public static SellerDirectShipment CreateWithId(
        Guid id,
        Guid orderId,
        string shipmentIdDisplay,
        string internalTrackingCode,
        string qrPayload,
        string qrCodeUrl,
        DateTime nowUtc)
    {
        return new SellerDirectShipment(
            SellerDirectShipmentId.From(id),
            OrderId.From(orderId),
            shipmentIdDisplay,
            internalTrackingCode,
            qrPayload,
            qrCodeUrl,
            nowUtc);
    }

    /// <summary>
    /// Sets or updates carrier info. Allowed only while the shipment is in
    /// Draft or CarrierBooked. Transitions Draft → CarrierBooked on the first
    /// successful set. Locked once the shipment is PickedUp or beyond.
    /// </summary>
    public UnitResult<Error> SetCarrierInfo(string carrierName, string externalTrackingCode, DateTime nowUtc)
    {
        if (Status != SellerDirectShipmentStatus.Draft &&
            Status != SellerDirectShipmentStatus.CarrierBooked)
            return SellerDirectShipmentErrors.SellerDirectShipment.CarrierInfoLocked;

        ExternalCarrierName  = carrierName;
        ExternalTrackingCode = externalTrackingCode;

        if (Status == SellerDirectShipmentStatus.Draft)
        {
            Status          = SellerDirectShipmentStatus.CarrierBooked;
            CarrierBookedAt = nowUtc;
        }

        ModifiedAt = nowUtc;
        return UnitResult.Success<Error>();
    }

    public UnitResult<Error> MarkPickedUp(DateTime nowUtc)
    {
        // Idempotent: already at or past PickedUp.
        if (Status == SellerDirectShipmentStatus.PickedUp ||
            Status == SellerDirectShipmentStatus.OnDelivering ||
            Status == SellerDirectShipmentStatus.Delivered ||
            Status == SellerDirectShipmentStatus.Accepted ||
            Status == SellerDirectShipmentStatus.Disputed ||
            Status == SellerDirectShipmentStatus.Completed)
            return UnitResult.Success<Error>();

        if (string.IsNullOrWhiteSpace(ExternalCarrierName) ||
            string.IsNullOrWhiteSpace(ExternalTrackingCode))
            return SellerDirectShipmentErrors.SellerDirectShipment.CarrierInfoRequired;

        // Require at least one seller package photo (dispatch details).
        var hasPackagePhoto = _evidence.Any(e =>
            e.Kind == SellerDirectShipmentEvidenceKind.SellerPackagePhoto);
        if (!hasPackagePhoto)
            return SellerDirectShipmentErrors.SellerDirectShipment.DispatchDetailsIncomplete;

        if (Status != SellerDirectShipmentStatus.Draft &&
            Status != SellerDirectShipmentStatus.CarrierBooked)
            return SellerDirectShipmentErrors.SellerDirectShipment.InvalidTransition(Status.Id, "mark picked up");

        Status     = SellerDirectShipmentStatus.PickedUp;
        PickedUpAt = nowUtc;
        ModifiedAt = nowUtc;
        return UnitResult.Success<Error>();
    }

    public UnitResult<Error> MarkOnDelivering(DateTime nowUtc)
    {
        if (Status == SellerDirectShipmentStatus.OnDelivering ||
            Status == SellerDirectShipmentStatus.Delivered ||
            Status == SellerDirectShipmentStatus.Accepted ||
            Status == SellerDirectShipmentStatus.Disputed ||
            Status == SellerDirectShipmentStatus.Completed)
            return UnitResult.Success<Error>();

        if (Status != SellerDirectShipmentStatus.PickedUp)
            return SellerDirectShipmentErrors.SellerDirectShipment.InvalidTransition(Status.Id, "mark on delivering");

        Status         = SellerDirectShipmentStatus.OnDelivering;
        OnDeliveringAt = nowUtc;
        ModifiedAt     = nowUtc;
        return UnitResult.Success<Error>();
    }

    public UnitResult<Error> MarkDelivered(DateTime nowUtc)
    {
        if (Status == SellerDirectShipmentStatus.Delivered ||
            Status == SellerDirectShipmentStatus.Accepted ||
            Status == SellerDirectShipmentStatus.Disputed ||
            Status == SellerDirectShipmentStatus.Completed)
            return UnitResult.Success<Error>();

        if (Status != SellerDirectShipmentStatus.OnDelivering)
            return SellerDirectShipmentErrors.SellerDirectShipment.InvalidTransition(Status.Id, "mark delivered");

        Status      = SellerDirectShipmentStatus.Delivered;
        DeliveredAt = nowUtc;
        ModifiedAt  = nowUtc;
        return UnitResult.Success<Error>();
    }

    /// <summary>
    /// Buyer-driven Delivered transition used by the proof-of-delivery flow.
    /// Allowed from PickedUp, OnDelivering, or already-Delivered (idempotent).
    /// Rejects Draft/CarrierBooked (package hasn't left the seller yet) and
    /// any terminal state (Accepted/Disputed/Completed).
    /// </summary>
    public UnitResult<Error> MarkDeliveredFromBuyerProof(DateTime nowUtc)
    {
        if (Status == SellerDirectShipmentStatus.Delivered)
        {
            DeliveredAt ??= nowUtc;
            return UnitResult.Success<Error>();
        }

        if (Status != SellerDirectShipmentStatus.PickedUp &&
            Status != SellerDirectShipmentStatus.OnDelivering)
            return SellerDirectShipmentErrors.SellerDirectShipment.InvalidTransition(
                Status.Id, "mark delivered from buyer proof");

        Status      = SellerDirectShipmentStatus.Delivered;
        DeliveredAt = nowUtc;
        ModifiedAt  = nowUtc;
        return UnitResult.Success<Error>();
    }

    /// <summary>
    /// Buyer stamps that they physically received the package. Stamp-only —
    /// does NOT change Status. Idempotent: subsequent calls leave the original
    /// timestamp untouched.
    /// </summary>
    public UnitResult<Error> AcknowledgeReceived(DateTime nowUtc)
    {
        if (BuyerReceivedPackageAt is not null)
            return UnitResult.Success<Error>();

        BuyerReceivedPackageAt = nowUtc;
        ModifiedAt             = nowUtc;
        return UnitResult.Success<Error>();
    }

    public UnitResult<Error> MarkAccepted(DateTime nowUtc)
    {
        if (Status == SellerDirectShipmentStatus.Accepted ||
            Status == SellerDirectShipmentStatus.Completed)
            return UnitResult.Success<Error>();

        if (Status != SellerDirectShipmentStatus.Delivered)
            return SellerDirectShipmentErrors.SellerDirectShipment.InvalidTransition(Status.Id, "mark accepted");

        Status          = SellerDirectShipmentStatus.Accepted;
        BuyerAcceptedAt = nowUtc;
        ModifiedAt      = nowUtc;
        return UnitResult.Success<Error>();
    }

    public UnitResult<Error> MarkDisputed(DateTime nowUtc)
    {
        if (Status == SellerDirectShipmentStatus.Disputed)
            return UnitResult.Success<Error>();

        if (Status != SellerDirectShipmentStatus.Delivered)
            return SellerDirectShipmentErrors.SellerDirectShipment.InvalidTransition(Status.Id, "mark disputed");

        Status     = SellerDirectShipmentStatus.Disputed;
        DisputedAt = nowUtc;
        ModifiedAt = nowUtc;
        return UnitResult.Success<Error>();
    }

    /// <summary>
    /// Attaches an evidence photo to the shipment. Wave A seed: simply appends
    /// the entity. Command-layer guards (status checks, per-kind limits) are
    /// wired in Wave B / C.
    /// </summary>
    public UnitResult<Error> AddEvidence(
        SellerDirectShipmentEvidenceKind kind,
        MediaUploadId mediaUploadId,
        string mediaUrl,
        Guid userId,
        DateTime nowUtc)
    {
        _evidence.Add(SellerDirectShipmentEvidence.Create(
            Id,
            kind,
            mediaUploadId,
            mediaUrl,
            userId,
            nowUtc));
        ModifiedAt = nowUtc;
        return UnitResult.Success<Error>();
    }

    /// <summary>
    /// Flags the shipment for manual review. Idempotent — subsequent calls
    /// leave the original reason untouched.
    /// </summary>
    public UnitResult<Error> FlagManualReview(string reason, DateTime nowUtc)
    {
        if (ManualReviewRequired) return UnitResult.Success<Error>();

        ManualReviewRequired = true;
        ManualReviewReason   = reason;
        ModifiedAt           = nowUtc;
        return UnitResult.Success<Error>();
    }

    /// <summary>
    /// Records the seller's self-declared dispatch timestamp, distinct from
    /// platform-observed <see cref="CarrierBookedAt"/> / <see cref="PickedUpAt"/>.
    /// </summary>
    public UnitResult<Error> RecordSellerDeclaredShippedAt(DateTime shippedAt, DateTime nowUtc)
    {
        SellerDeclaredShippedAt = DateTime.SpecifyKind(shippedAt, DateTimeKind.Utc);
        ModifiedAt              = nowUtc;
        return UnitResult.Success<Error>();
    }

    /// <summary>
    /// Captures the buyer-reported package condition at receipt. Allowed
    /// values are enforced at the command layer.
    /// </summary>
    public UnitResult<Error> SetBuyerCondition(string condition, string? notes, DateTime nowUtc)
    {
        BuyerPackageCondition = condition;
        BuyerConditionNotes   = notes;
        ModifiedAt            = nowUtc;
        return UnitResult.Success<Error>();
    }

    /// <summary>
    /// Replaces the stored QR payload/url. Used by the backfill job to migrate
    /// legacy shipments whose <see cref="QrPayload"/> predates the signed-token
    /// scan URL format. Callers must separately record the new token issue
    /// via <see cref="RecordQrTokenIssued"/>.
    /// </summary>
    public UnitResult<Error> OverwriteQrPayload(string qrPayload, string qrCodeUrl, DateTime nowUtc)
    {
        QrPayload  = qrPayload;
        QrCodeUrl  = qrCodeUrl;
        ModifiedAt = nowUtc;
        return UnitResult.Success<Error>();
    }

    /// <summary>
    /// Records the issue time/version of the QR token. Wave B: called by the
    /// create command immediately after the initial token is minted.
    /// </summary>
    public UnitResult<Error> RecordQrTokenIssued(int version, DateTime issuedAt, DateTime nowUtc)
    {
        QrTokenVersion   = version;
        QrTokenIssuedAt  = DateTime.SpecifyKind(issuedAt, DateTimeKind.Utc);
        QrTokenRevokedAt = null;
        ModifiedAt       = nowUtc;
        return UnitResult.Success<Error>();
    }

    /// <summary>
    /// Revokes the current QR token. Idempotent — a previously revoked token
    /// stays revoked with its original timestamp.
    /// </summary>
    public UnitResult<Error> RevokeQrToken(DateTime nowUtc)
    {
        if (QrTokenRevokedAt is not null) return UnitResult.Success<Error>();

        QrTokenRevokedAt = nowUtc;
        ModifiedAt       = nowUtc;
        return UnitResult.Success<Error>();
    }

    public UnitResult<Error> MarkCompleted(DateTime nowUtc)
    {
        if (Status == SellerDirectShipmentStatus.Completed)
            return UnitResult.Success<Error>();

        if (Status != SellerDirectShipmentStatus.Accepted)
            return SellerDirectShipmentErrors.SellerDirectShipment.InvalidTransition(Status.Id, "mark completed");

        Status      = SellerDirectShipmentStatus.Completed;
        CompletedAt = nowUtc;
        ModifiedAt  = nowUtc;
        return UnitResult.Success<Error>();
    }
}
