services:
  database:
    image: "postgres:17.6"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  oio.api:
    image: "ghcr.io/sep490-oio/backend/oio-api:${APP_VERSION:-latest}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__Database=Host=database;Port=5432;Username=postgres;Password=${DATABASE_PASSWORD};Database=oio-mcbc;Include Error Detail=true;
      - ConnectionStrings__Cache=redis:6379
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - MediatR__LicenseKey=${MEDIATR_LICENSE_KEY}
      - Email__Username=${EMAIL_USERNAME}
      - Email__Password=${EMAIL_PASSWORD}
      - DefaultAccount__Email=${DEFAULT_ACCOUNT_EMAIL}
      - DefaultAccount__UserName=${DEFAULT_ACCOUNT_USERNAME}
      - DefaultAccount__Password=${DEFAULT_ACCOUNT_PASSWORD}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq:5341/ingest/otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - Hashing__HmacKeyBase64=${HASHING_KEY}
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
      - VnptEkyc__AccessToken=${VNPT_EKYC_ACCESS_TOKEN}
      - VnptEkyc__TokenId=${VNPT_EKYC_TOKEN_ID}
      - VnptEkyc__TokenKey=${VNPT_EKYC_TOKEN_KEY}
      - VnPay__TmnCode=${VNPAY_TMN_CODE}
      - VnPay__HashSecret=${VNPAY_HASH_SECRET}
      - Elasticsearch__Endpoint=${Elasticsearch__Endpoint}
      - Elasticsearch__ApiKey=${Elasticsearch__ApiKey}
      - Ai__ProductDescription__ApiKey=${AI_PRODUCT_DESCRIPTION_API_KEY}
    volumes:
      - ./config/appsettings.Production.json:/app/appsettings.Production.json
    depends_on:
      - database
    restart: unless-stopped
        
  frontend:
    image: ghcr.io/sep490-oio/frontend:latest
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - oio.api
      - seq
      - frontend

  redis:
    image: redis:latest
    container_name: Redis
    restart: unless-stopped
  
#  seq:
#    image: datalust/seq:latest
#    container_name: Seq
#    environment:
#      - ACCEPT_EULA=Y
#      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_ADMIN_PASSWORD}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    labels:
      - "com.docker.compose.project=oio"

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
