<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AppAny.Quartz.EntityFrameworkCore.Migrations.PostgreSQL" Version="0.5.1" />
    <PackageVersion Include="Aspire.Hosting.Docker" Version="13.1.2-preview.1.26125.13" />
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.1.2" />
    <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.Uris" Version="9.0.0" />
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="CloudinaryDotNet" Version="1.28.0" />
    <PackageVersion Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageVersion Include="CSharpFunctionalExtensions.HttpResults" Version="1.2.1" />
    <PackageVersion Include="Dapper" Version="2.1.66" />
    <PackageVersion Include="EFCore.ComplexIndexes.PostgreSQL" Version="2.0.0" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageVersion Include="FormatWith" Version="3.0.1" />
    <PackageVersion Include="libphonenumber-csharp" Version="9.0.23" />
    <PackageVersion Include="MailKit" Version="4.15.1" />
    <PackageVersion Include="MediatR" Version="14.0.0" />
    <PackageVersion Include="MediatR.Contracts" Version="2.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="10.0.6" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.0.0" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Hybrid" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="10.0.0" />
    <PackageVersion Include="Npgsql.DependencyInjection" Version="10.0.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageVersion Include="Npgsql.OpenTelemetry" Version="10.0.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Quartz" Version="1.15.0-beta.1" />
    <PackageVersion Include="Otp.NET" Version="1.4.1" />
    <PackageVersion Include="QRCoder" Version="1.7.0" />
    <PackageVersion Include="Quartz.Extensions.DependencyInjection" Version="3.16.1" />
    <PackageVersion Include="Quartz.Extensions.Hosting" Version="3.16.0" />
    <PackageVersion Include="Quartz.Serialization.Json" Version="3.16.1" />
    <PackageVersion Include="Quartz.Serialization.SystemTextJson" Version="3.16.1" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.12.46" />
    <PackageVersion Include="Scrutor" Version="7.0.0" />
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Seq" Version="9.0.0" />
    <PackageVersion Include="SignalRSwaggerGen" Version="4.9.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.0.0" />
    <PackageVersion Include="System.Linq.Dynamic.Core" Version="1.7.1" />
    <PackageVersion Include="Vogen" Version="8.0.4" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
    <PackageVersion Include="Elastic.Clients.Elasticsearch" Version="8.17.1" />
  </ItemGroup>
</Project>