<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UserSecretsId>aebb9954-4e65-46c1-83b3-1bbb23e2658b</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\presentation\OIO.Api\OIO.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Docker" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>

</Project>
