namespace OIO.Application.Context.AuctionContext.DTOs;

public sealed record AuctionListItemDto(
    Guid Id,
    string ItemTitle,
    string? PrimaryImageUrl,
    MoneyDto CurrentPrice,
    MoneyDto StartingPrice,
    MoneyDto? BuyNowPrice,
    bool IsBuyNowReserved,
    DateTime? BuyNowReservedUntil,
    string Currency,
    string Status,
    int BidCount,
    int WatchCount,
    int ViewCount,
    DateTime? StartTime,
    DateTime? EndTime,
    TimeSpan? RemainingTime,
    DateTime CreatedAt,
    bool? IsEndingSoon,
    bool? IsFeatured,
    Guid SellerId,
    string ItemStatus,
    string AuctionType);
