<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
      <ProjectReference Include="..\..\aspire\OIO.ServiceDefaults\OIO.ServiceDefaults.csproj" />
      <ProjectReference Include="..\..\core\OIO.Application\OIO.Application.csproj" />
      <ProjectReference Include="..\..\infrastructure\OIO.Infrastructure\OIO.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Scalar.AspNetCore" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    </ItemGroup>

</Project>
