// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OIO.Infrastructure.Persistence;

#nullable disable

namespace OIO.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260307065557_add_system_settings")]
    partial class add_system_settings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_time");

                    b.Property<bool>("AutoExtend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_extend");

                    b.Property<int>("BidCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("bid_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CurrentWinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.Property<int>("ExtensionMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("extension_minutes");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<int>("WatchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("watch_count");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BidIncrement", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction.BidIncrement#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("numeric(18,2)")
                                .HasDefaultValue(1.00m)
                                .HasColumnName("bid_increment");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BuyNowPrice", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction.BuyNowPrice#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("buy_now_price");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CurrentPrice", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction.CurrentPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("current_price");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Duration", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction.Duration#AuctionDuration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("EndTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_time")
                                .HasAnnotation("CustomIndex:IsIndexed", true)
                                .HasAnnotation("CustomIndex:IsUnique", false)
                                .HasAnnotation("CustomIndex:Name", "idx_auctions_end_time");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_time")
                                .HasAnnotation("CustomIndex:IsIndexed", true)
                                .HasAnnotation("CustomIndex:IsUnique", false)
                                .HasAnnotation("CustomIndex:Name", "idx_auctions_start_time");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ReservePrice", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction.ReservePrice#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("reserve_price");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StartingPrice", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction.StartingPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("starting_price");
                        });

                    b.HasKey("Id")
                        .HasName("pk_auctions");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_auctions_status");

                    b.ToTable("auctions", null, t =>
                        {
                            t.HasCheckConstraint("chk_buy_now_gt_starting", "buy_now_price > starting_price");

                            t.HasCheckConstraint("chk_current_gte_starting", "current_price >= starting_price");

                            t.HasCheckConstraint("chk_end_after_start", "end_time > start_time");

                            t.HasCheckConstraint("chk_positive_bid_increment", "bid_increment > 0");

                            t.HasCheckConstraint("chk_reserve_gte_starting", "reserve_price >= starting_price");
                        });
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AuctionPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<Guid?>("BidId")
                        .HasColumnType("uuid")
                        .HasColumnName("bid_id");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AuctionPriceHistory.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price");
                        });

                    b.HasKey("Id")
                        .HasName("pk_auction_price_history");

                    b.HasIndex("AuctionId")
                        .HasDatabaseName("ix_auction_price_history_auction_id");

                    b.ToTable("auction_price_history", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AuctionWatcher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("NotifyOnBid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_on_bid");

                    b.Property<bool>("NotifyOnEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_on_end");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auction_watchers");

                    b.HasIndex("AuctionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_auction_watchers_auction_id_user_id");

                    b.ToTable("auction_watchers", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AutoBid", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bidder_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastAutoBidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_auto_bid_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<int>("TotalAutoBids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_auto_bids");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CurrentAmount", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AutoBid.CurrentAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("current_amount");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "IncrementAmount", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AutoBid.IncrementAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("increment_amount");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MaxAmount", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AutoBid.MaxAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("max_amount");
                        });

                    b.HasKey("Id")
                        .HasName("pk_auction_auto_bids");

                    b.HasIndex("AuctionId")
                        .HasDatabaseName("idx_auction_auto_bids_auction_id");

                    b.HasIndex("BidderId")
                        .HasDatabaseName("idx_auction_auto_bids_bidder_id");

                    b.HasIndex("AuctionId", "BidderId")
                        .IsUnique()
                        .HasDatabaseName("ix_auction_auto_bids_auction_id_bidder_id");

                    b.HasIndex("AuctionId", "Status")
                        .HasDatabaseName("idx_auction_auto_bids_auction_id_status")
                        .HasFilter("status = 'active'");

                    b.ToTable("auction_auto_bids", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<Guid?>("AutoBidId")
                        .HasColumnType("uuid")
                        .HasColumnName("auto_bid_id");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bidder_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsAutoBid")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_bid")
                        .HasComputedColumnSql("(auto_bid_id IS NOT NULL)", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Bid.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");
                        });

                    b.HasKey("Id")
                        .HasName("pk_bids");

                    b.HasIndex("AuctionId")
                        .HasDatabaseName("idx_bids_auction");

                    b.HasIndex("AutoBidId")
                        .HasDatabaseName("ix_bids_auto_bid_id");

                    b.HasIndex("BidderId")
                        .HasDatabaseName("idx_bids_bidder");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_items_category");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("idx_items_seller");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Items.ItemMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Format")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("public_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("resource_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_item_media");

                    b.HasIndex("PublicId")
                        .HasDatabaseName("idx_item_media_public_id");

                    b.HasIndex("ItemId", "ResourceType")
                        .HasDatabaseName("idx_item_media_item_type");

                    b.ToTable("item_media", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Items.ItemQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("AskerId")
                        .HasColumnType("uuid")
                        .HasColumnName("asker_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("Id")
                        .HasName("pk_item_questions");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_questions_item_id");

                    b.ToTable("item_questions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.Shared.Entities.MediaUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("folder");

                    b.Property<string>("Format")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_confirmed");

                    b.Property<bool>("IsLinked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_linked");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("public_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("resource_type");

                    b.Property<string>("SecureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("secure_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media_uploads");

                    b.HasIndex("PublicId")
                        .HasDatabaseName("idx_media_uploads_public_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_media_uploads_user_id");

                    b.HasIndex("IsConfirmed", "ExpiresAt")
                        .HasDatabaseName("idx_media_uploads_expired")
                        .HasFilter("is_confirmed = false");

                    b.HasIndex("IsConfirmed", "IsLinked", "ConfirmedAt")
                        .HasDatabaseName("idx_media_uploads_orphan")
                        .HasFilter("is_confirmed = true AND is_linked = false");

                    b.ToTable("media_uploads", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.Shared.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_system_settings");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedPermissionCode")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_permission_code")
                        .HasComputedColumnSql("UPPER(permission_code)", true);

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("permission_code");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("NormalizedPermissionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_normalized_permission_code");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedRoleName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_role_name")
                        .HasComputedColumnSql("UPPER(role_name)", true);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedRoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_role_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("LockoutReason")
                        .HasColumnType("text")
                        .HasColumnName("lockout_reason");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<DateTime?>("PhoneNumberConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_number_confirmed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("inactive")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("none")
                        .HasColumnName("two_factor_provider");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "OIO.Domain.Context.UserContext.Aggregates.Users.User.Email#UserEmail", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("normalized_email")
                                .HasComputedColumnSql("upper((email)::text)", true)
                                .HasAnnotation("CustomIndex:Filter", "(deleted_at IS NULL)")
                                .HasAnnotation("CustomIndex:IsIndexed", true)
                                .HasAnnotation("CustomIndex:IsUnique", true)
                                .HasAnnotation("CustomIndex:Name", "idx_unique_users_normalized_email_active");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "OIO.Domain.Context.UserContext.Aggregates.Users.User.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone_number");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UserName", "OIO.Domain.Context.UserContext.Aggregates.Users.User.UserName#UserName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("normalized_user_name")
                                .HasComputedColumnSql("upper((user_name)::text)", true)
                                .HasAnnotation("CustomIndex:Filter", "(deleted_at IS NULL)")
                                .HasAnnotation("CustomIndex:IsIndexed", true)
                                .HasAnnotation("CustomIndex:IsUnique", true)
                                .HasAnnotation("CustomIndex:Name", "idx_unique_users_normalized_user_name_active");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("user_name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("other")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("district");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("address");

                            b1.Property<string>("Ward")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ward");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone_number");
                        });

                    b.HasKey("Id")
                        .HasName("pk_user_addresses");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_unique_default_address_per_user")
                        .HasFilter("is_default = TRUE");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("idx_user_addresses_user_id_type");

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserLoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_login_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_login_history_user_id");

                    b.ToTable("user_login_history", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<bool>("IsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_allowed");

                    b.HasKey("UserId", "PermissionId")
                        .HasName("pk_user_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_user_permissions_permission_id");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<IPAddress>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<IPAddress>("RevokedByIp")
                        .HasColumnType("inet")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<int>("RotationCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rotation_counter");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_refresh_tokens_expires_at");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("ix_user_refresh_tokens_parent_token_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_user_refresh_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_refresh_tokens_token_hash");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("ix_user_refresh_tokens_session_session_id_created_at");

                    b.HasIndex("UserId", "IsUsed")
                        .HasDatabaseName("ix_user_refresh_tokens_user_id_is_used");

                    b.ToTable("user_refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("chk_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("chk_revoked_after_created", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("chk_used_after_created", "used_at IS NULL OR used_at >= created_at");
                        });
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastRotatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rotated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("AbsoluteExpiresAt")
                        .HasDatabaseName("ix_user_sessions_absolute_expires_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_sessions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_user_sessions_user_active");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("OIO.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("OccurredAt", "Id")
                        .HasDatabaseName("idx_outbox_cleanup")
                        .HasFilter("processed_at IS NOT NULL AND error IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("OIO.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AuctionPriceHistory", b =>
                {
                    b.HasOne("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction", null)
                        .WithMany("PriceHistories")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auction_price_history_auctions_auction_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AuctionWatcher", b =>
                {
                    b.HasOne("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction", null)
                        .WithMany("Watchers")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auction_watchers_auctions_auction_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AutoBid", b =>
                {
                    b.HasOne("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction", null)
                        .WithMany("AutoBids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auction_auto_bids_auctions_auction_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Bid", b =>
                {
                    b.HasOne("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction", null)
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bids_auctions_auction_id");

                    b.HasOne("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.AutoBid", null)
                        .WithMany()
                        .HasForeignKey("AutoBidId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bids_auction_auto_bids_auto_bid_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Categories.Category", b =>
                {
                    b.HasOne("OIO.Domain.Context.AuctionContext.Aggregates.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Items.ItemMedia", b =>
                {
                    b.HasOne("OIO.Domain.Context.AuctionContext.Aggregates.Items.Item", null)
                        .WithMany("Media")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_media_items_item_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Items.ItemQuestion", b =>
                {
                    b.HasOne("OIO.Domain.Context.AuctionContext.Aggregates.Items.Item", null)
                        .WithMany("Questions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_questions_items_item_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.RolePermission", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_addresses_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserLoginHistory", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_login_history_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserPermission", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_permissions_permission_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserProfile", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithOne("Profile")
                        .HasForeignKey("OIO.Domain.Context.UserContext.Aggregates.Users.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_users_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshToken", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ParentTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_refresh_tokens_user_refresh_tokens_parent_token_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.UserSession", "RefreshTokenFamily")
                        .WithMany("Tokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_tokens_user_sessions_session_id");

                    b.Navigation("RefreshTokenFamily");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRole", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserSession", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Auctions.Auction", b =>
                {
                    b.Navigation("AutoBids");

                    b.Navigation("Bids");

                    b.Navigation("PriceHistories");

                    b.Navigation("Watchers");
                });

            modelBuilder.Entity("OIO.Domain.Context.AuctionContext.Aggregates.Items.Item", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("LoginHistories");

                    b.Navigation("Permissions");

                    b.Navigation("Profile");

                    b.Navigation("Roles");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserSession", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
