// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OIO.Infrastructure.Persistence;

#nullable disable

namespace OIO.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223092634_change_to_id_value_never_generated")]
    partial class change_to_id_value_never_generated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedPermissionCode")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_permission_code")
                        .HasComputedColumnSql("UPPER(permission_code)", true);

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("permission_code");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("NormalizedPermissionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_normalized_permission_code");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedRoleName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_role_name")
                        .HasComputedColumnSql("UPPER(role_name)", true);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedRoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_role_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("LockoutReason")
                        .HasColumnType("text")
                        .HasColumnName("lockout_reason");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<DateTime?>("PhoneNumberConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_number_confirmed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("inactive")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("none")
                        .HasColumnName("two_factor_provider");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("other")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_addresses");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_unique_default_address_per_user")
                        .HasFilter("is_default = TRUE");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("idx_user_addresses_user_id_type");

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserLoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_login_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_login_history_user_id");

                    b.ToTable("user_login_history", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<bool>("IsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_allowed");

                    b.HasKey("UserId", "PermissionId")
                        .HasName("pk_user_permissions");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<IPAddress>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<IPAddress>("RevokedByIp")
                        .HasColumnType("inet")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<int>("RotationCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rotation_counter");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_refresh_tokens_expires_at");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_user_refresh_tokens_family_id");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("ix_user_refresh_tokens_parent_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_refresh_tokens_token_hash");

                    b.HasIndex("FamilyId", "CreatedAt")
                        .HasDatabaseName("ix_user_refresh_tokens_family_family_id_created_at");

                    b.HasIndex("UserId", "IsUsed")
                        .HasDatabaseName("ix_user_refresh_tokens_user_id_is_used");

                    b.ToTable("user_refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("chk_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("chk_revoked_after_created", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("chk_used_after_created", "used_at IS NULL OR used_at >= created_at");
                        });
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshTokenFamily", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastRotatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rotated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_refresh_token_families");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_refresh_token_families_user");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_user_refresh_token_families_user_active");

                    b.ToTable("user_refresh_token_families", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("OIO.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("OccurredAt", "Id")
                        .HasDatabaseName("idx_outbox_cleanup")
                        .HasFilter("processed_at IS NOT NULL AND error IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.RolePermission", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.User", b =>
                {
                    b.OwnsOne("OIO.Domain.Context.UserContext.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone_number");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("OIO.Domain.Context.UserContext.ValueObjects.UserEmail", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("normalized_email")
                                .HasComputedColumnSql("upper((email)::text)", true);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex(new[] { "Normalized" }, "idx_unique_users_normalized_email_active")
                                .IsUnique()
                                .HasDatabaseName("ix_users_normalized_email")
                                .HasFilter("(deleted_at IS NULL)");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("OIO.Domain.Context.UserContext.ValueObjects.UserName", "UserName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("normalized_user_name")
                                .HasComputedColumnSql("upper((user_name)::text)", true);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("user_name");

                            b1.HasKey("UserId");

                            b1.HasIndex(new[] { "Normalized" }, "idx_unique_users_normalized_user_name_active")
                                .IsUnique()
                                .HasDatabaseName("ix_users_normalized_user_name")
                                .HasFilter("(deleted_at IS NULL)");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber");

                    b.Navigation("UserName")
                        .IsRequired();
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_addresses_users_user_id");

                    b.OwnsOne("OIO.Domain.Context.UserContext.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserAddressId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone_number");

                            b1.HasKey("UserAddressId");

                            b1.ToTable("user_addresses");

                            b1.WithOwner()
                                .HasForeignKey("UserAddressId")
                                .HasConstraintName("fk_user_addresses_user_addresses_id");
                        });

                    b.OwnsOne("OIO.Domain.Context.UserContext.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserAddressId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("district");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("address");

                            b1.Property<string>("Ward")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ward");

                            b1.HasKey("UserAddressId");

                            b1.ToTable("user_addresses");

                            b1.WithOwner()
                                .HasForeignKey("UserAddressId")
                                .HasConstraintName("fk_user_addresses_user_addresses_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserLoginHistory", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_login_history_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserPermission", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserProfile", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithOne("Profile")
                        .HasForeignKey("OIO.Domain.Context.UserContext.Aggregates.Users.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_users_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshToken", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshTokenFamily", null)
                        .WithMany("Tokens")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_tokens_user_refresh_token_families_family_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ParentTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_refresh_tokens_user_refresh_tokens_parent_token_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshTokenFamily", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("RefreshTokenFamilies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_token_families_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRole", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("LoginHistories");

                    b.Navigation("Permissions");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokenFamilies");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshTokenFamily", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
