// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OIO.Infrastructure.Persistence;

#nullable disable

namespace OIO.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304180422_NotificationMigration")]
    partial class NotificationMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OIO.Domain.Context.NotificationContext.Aggregates.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notification_type");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Actions", "OIO.Domain.Context.NotificationContext.Aggregates.Notifications.Notification.Actions#NotificationActions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("actions");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Metadata", "OIO.Domain.Context.NotificationContext.Aggregates.Notifications.Notification.Metadata#NotificationMetadata", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RelatedEntities", "OIO.Domain.Context.NotificationContext.Aggregates.Notifications.Notification.RelatedEntities#RelatedEntities", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("related_entities");
                        });

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_notifications_entity");

                    b.HasIndex("NotificationType", "EventType")
                        .HasDatabaseName("idx_notifications_type_event");

                    b.HasIndex("Priority", "CreatedAt")
                        .HasDatabaseName("idx_notifications_priority_created");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("idx_notifications_user_created");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_notifications_user_status");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.NotificationContext.Aggregates.Notifications.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Error", "OIO.Domain.Context.NotificationContext.Aggregates.Notifications.NotificationDelivery.Error#DeliveryError", b1 =>
                        {
                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("error_code");

                            b1.Property<string>("DetailsJson")
                                .HasColumnType("jsonb")
                                .HasColumnName("error_details");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("error_message");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Metadata", "OIO.Domain.Context.NotificationContext.Aggregates.Notifications.NotificationDelivery.Metadata#DeliveryMetadata", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("delivery_metadata");
                        });

                    b.HasKey("Id")
                        .HasName("pk_notification_delivery");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("idx_delivery_retry");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("idx_delivery_notification");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("idx_delivery_status_scheduled");

                    b.HasIndex("UserId", "Channel")
                        .HasDatabaseName("idx_delivery_user_channel");

                    b.ToTable("notification_delivery", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.NotificationContext.Aggregates.UserNotificationPreferences.UserNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Channels", "OIO.Domain.Context.NotificationContext.Aggregates.UserNotificationPreferences.UserNotificationPreference.Channels#NotificationChannels", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("channels");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "QuietHours", "OIO.Domain.Context.NotificationContext.Aggregates.UserNotificationPreferences.UserNotificationPreference.QuietHours#QuietHours", b1 =>
                        {
                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("quiet_hours");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RateLimits", "OIO.Domain.Context.NotificationContext.Aggregates.UserNotificationPreferences.UserNotificationPreference.RateLimits#NotificationRateLimits", b1 =>
                        {
                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("rate_limits");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TypePreferences", "OIO.Domain.Context.NotificationContext.Aggregates.UserNotificationPreferences.UserNotificationPreference.TypePreferences#TypePreferences", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("type_preferences");
                        });

                    b.HasKey("Id")
                        .HasName("pk_user_notification_preferences");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_preferences_user");

                    b.ToTable("user_notification_preferences", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedPermissionCode")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_permission_code")
                        .HasComputedColumnSql("UPPER(permission_code)", true);

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("permission_code");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("NormalizedPermissionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_normalized_permission_code");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedRoleName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_role_name")
                        .HasComputedColumnSql("UPPER(role_name)", true);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedRoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_role_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("LockoutReason")
                        .HasColumnType("text")
                        .HasColumnName("lockout_reason");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<DateTime?>("PhoneNumberConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_number_confirmed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("inactive")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("none")
                        .HasColumnName("two_factor_provider");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "OIO.Domain.Context.UserContext.Aggregates.Users.User.Email#UserEmail", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("normalized_email")
                                .HasComputedColumnSql("upper((email)::text)", true)
                                .HasAnnotation("CustomIndex:Filter", "(deleted_at IS NULL)")
                                .HasAnnotation("CustomIndex:IsIndexed", true)
                                .HasAnnotation("CustomIndex:IsUnique", true)
                                .HasAnnotation("CustomIndex:Name", "idx_unique_users_normalized_email_active");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "OIO.Domain.Context.UserContext.Aggregates.Users.User.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone_number");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UserName", "OIO.Domain.Context.UserContext.Aggregates.Users.User.UserName#UserName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("normalized_user_name")
                                .HasComputedColumnSql("upper((user_name)::text)", true)
                                .HasAnnotation("CustomIndex:Filter", "(deleted_at IS NULL)")
                                .HasAnnotation("CustomIndex:IsIndexed", true)
                                .HasAnnotation("CustomIndex:IsUnique", true)
                                .HasAnnotation("CustomIndex:Name", "idx_unique_users_normalized_user_name_active");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("user_name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("other")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("district");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("address");

                            b1.Property<string>("Ward")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ward");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone_number");
                        });

                    b.HasKey("Id")
                        .HasName("pk_user_addresses");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_unique_default_address_per_user")
                        .HasFilter("is_default = TRUE");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("idx_user_addresses_user_id_type");

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserLoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_login_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_login_history_user_id");

                    b.ToTable("user_login_history", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<bool>("IsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_allowed");

                    b.HasKey("UserId", "PermissionId")
                        .HasName("pk_user_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_user_permissions_permission_id");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<IPAddress>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<IPAddress>("RevokedByIp")
                        .HasColumnType("inet")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<int>("RotationCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rotation_counter");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_refresh_tokens_expires_at");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("ix_user_refresh_tokens_parent_token_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_user_refresh_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_refresh_tokens_token_hash");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("ix_user_refresh_tokens_session_session_id_created_at");

                    b.HasIndex("UserId", "IsUsed")
                        .HasDatabaseName("ix_user_refresh_tokens_user_id_is_used");

                    b.ToTable("user_refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("chk_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("chk_revoked_after_created", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("chk_used_after_created", "used_at IS NULL OR used_at >= created_at");
                        });
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastRotatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rotated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("AbsoluteExpiresAt")
                        .HasDatabaseName("ix_user_sessions_absolute_expires_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_sessions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_user_sessions_user_active");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("OIO.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("OccurredAt", "Id")
                        .HasDatabaseName("idx_outbox_cleanup")
                        .HasFilter("processed_at IS NOT NULL AND error IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("OIO.Domain.Context.NotificationContext.Aggregates.Notifications.Notification", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.NotificationContext.Aggregates.Notifications.NotificationDelivery", b =>
                {
                    b.HasOne("OIO.Domain.Context.NotificationContext.Aggregates.Notifications.Notification", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_delivery_notifications_notification_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_delivery_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.NotificationContext.Aggregates.UserNotificationPreferences.UserNotificationPreference", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notification_preferences_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.RolePermission", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserAddress", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_addresses_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserLoginHistory", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_login_history_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserPermission", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_permissions_permission_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserProfile", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithOne("Profile")
                        .HasForeignKey("OIO.Domain.Context.UserContext.Aggregates.Users.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_users_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshToken", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.UserRefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ParentTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_refresh_tokens_user_refresh_tokens_parent_token_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.UserSession", "RefreshTokenFamily")
                        .WithMany("Tokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_tokens_user_sessions_session_id");

                    b.Navigation("RefreshTokenFamily");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserRole", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserSession", b =>
                {
                    b.HasOne("OIO.Domain.Context.UserContext.Aggregates.Users.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");
                });

            modelBuilder.Entity("OIO.Domain.Context.NotificationContext.Aggregates.Notifications.Notification", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Roles.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("LoginHistories");

                    b.Navigation("Permissions");

                    b.Navigation("Profile");

                    b.Navigation("Roles");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("OIO.Domain.Context.UserContext.Aggregates.Users.UserSession", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
