<Project Sdk="Microsoft.NET.Sdk.Razor">

    <ItemGroup>
      <PackageReference Include="AppAny.Quartz.EntityFrameworkCore.Migrations.PostgreSQL" />
      <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
      <PackageReference Include="AspNetCore.HealthChecks.Redis" />
      <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
      <PackageReference Include="AspNetCore.HealthChecks.Uris" />
      <PackageReference Include="Bogus" />
      <PackageReference Include="CloudinaryDotNet" />
      <PackageReference Include="EFCore.ComplexIndexes.PostgreSQL" />
      <PackageReference Include="EFCore.NamingConventions" />
      <PackageReference Include="MailKit" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
      <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
      <PackageReference Include="Npgsql.DependencyInjection" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Otp.NET" />
      <PackageReference Include="QRCoder" />
      <PackageReference Include="Quartz.Extensions.DependencyInjection" />
      <PackageReference Include="Quartz.Extensions.Hosting" />
      <PackageReference Include="Quartz.Serialization.Json" />
      <PackageReference Include="Quartz.Serialization.SystemTextJson" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\OIO.Application\OIO.Application.csproj" />
    </ItemGroup>

</Project>
