<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Persistence\Migrations\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
      <PackageReference Include="AspNetCore.HealthChecks.Redis" />
      <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
      <PackageReference Include="AspNetCore.HealthChecks.Uris" />
      <PackageReference Include="EFCore.ComplexIndexes.PostgreSQL" />
      <PackageReference Include="EFCore.NamingConventions" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
      <PackageReference Include="Npgsql.DependencyInjection" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Quartz.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\OIO.Application\OIO.Application.csproj" />
    </ItemGroup>

</Project>
