<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="libphonenumber-csharp" />
      <PackageReference Include="MediatR.Contracts" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Context\AuctionContext\" />
      <Folder Include="Context\DisputeContext\" />
      <Folder Include="Context\NotificationContext\" />
      <Folder Include="Context\PaymentContext\" />
      <Folder Include="Context\ReviewContext\" />
    </ItemGroup>

</Project>
