<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" />
      <PackageReference Include="CSharpFunctionalExtensions.HttpResults" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="FormatWith" />
      <PackageReference Include="libphonenumber-csharp" />
      <PackageReference Include="MediatR.Contracts" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
      <PackageReference Include="Microsoft.Orleans.Server" />
      <PackageReference Include="Vogen" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Context\DisputeContext\" />
      <Folder Include="Context\NotificationContext\" />
      <Folder Include="Context\PaymentContext\" />
      <Folder Include="Context\ReviewContext\" />
      <Folder Include="Context\WarehouseContext\Aggregates\ShippingProviders\Events\" />
      <Folder Include="Context\WarehouseContext\Aggregates\WarehouseStorage\Events\" />
      <Folder Include="Context\WarehouseContext\Services\" />
    </ItemGroup>

</Project>
